version: 2.1

orbs:
  gcp-gke: circleci/gcp-gke@1.4.0

executors:
  machine-executor:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/repo

jobs:

  build_and_push:
    executor: machine-executor
    steps:
      - checkout

      - run:
          name: Install Google Cloud SDK
          command: |
            sudo apt-get update
            sudo apt-get install -y google-cloud-sdk

      - run:
          name: Authenticate to GCP
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud config set project $GOOGLE_PROJECT_ID

      - run:
          name: Configure Docker for Artifact Registry
          command: |
            gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - run:
          name: Build Docker Image
          command: |
            docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/llmops-repo/llmops-app:$CIRCLE_SHA1 .

      - run:
          name: Push Docker Image
          command: |
            docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/llmops-repo/llmops-app:$CIRCLE_SHA1

  deploy_to_gke:
    executor: machine-executor
    steps:
      - checkout

      - run:
          name: Install Google Cloud SDK
          command: |
            sudo apt-get update
            sudo apt-get install -y google-cloud-sdk

      - run:
          name: Authenticate to GCP
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud config set project $GOOGLE_PROJECT_ID

      - run:
          name: Get GKE Credentials
          command: |
            gcloud container clusters get-credentials $GKE_CLUSTER \
              --region $GOOGLE_COMPUTE_REGION \
              --project $GOOGLE_PROJECT_ID

      - run:
          name: Update Deployment Image
          command: |
            kubectl set image deployment/llmops-app \
            llmops-app=us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/llmops-repo/llmops-app:$CIRCLE_SHA1

      - run:
          name: Verify Rollout
          command: |
            kubectl rollout status deployment/llmops-app

workflows:
  version: 2
  llmops_pipeline:
    jobs:
      - build_and_push
      - deploy_to_gke:
          requires:
            - build_and_push